[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
temp_project = "22oc9tz17ZY35UX1W5YFyr9WMN2T4ueYN2a5jpeKGUC9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
